### ISSUE TITLE
Keeping things clean

### ISSUE THREAD

**Issue by vsalbuq** [vsalbuq/FastFeet#1]
# Story
- **As a:** product owner
- **I want to:** enforce code style on my application
- **So that:** the code of the application may be kept clean
# Tasks
- [x] Add ESLint + Prettier + EditorConfig to the project;
- [x] Add ESLint's Airbnb code style plugin;
- [x] Add ESLint's Prettier plugin;
